variable "namespace" {}
variable "aws_sns_topic_subscription" {}
variable "pod" {}
variable "dbinstanceId" {}
variable "evaluation_periods" {}
variable "period" {}
variable "statistic" {}
variable "actions_enabled" {}
variable "cpu_threshold_warning" {}
variable "cpu_threshold_critical" {}
variable "freememory_threshold_warning" {}
variable "freememory_threshold_critical" {}
variable "diskspace_threshold_warning" {}
variable "diskspace_threshold_critical" {}
variable "rds_connections_threshold_warning" {}
variable "rds_connections_threshold_critical" {}
variable "rds_read_latency_threshold" {}
variable "rds_write_latency_threshold" {}
variable "rds_replica_lag_threshold" {}